[package]
name = "contract"
version = "0.0.0"
authors = [ "", ]
edition = "2018"
publish = false

[lib]
path = "src/contract.rs"

[features]
wasm-output-mode = ["elrond-wasm-node"]

[dependencies.elrond-wasm]
version = "0.18.2"
features = ["derive"]

[dependencies.elrond-wasm-node]
version = "0.18.2"
optional = true

[dev-dependencies.elrond-wasm-debug]
version = "0.18.2"
